// Pharmacy medicine catalog — built from the client's Medicine Data.
// Per requirement: NO brand names. drugName = Salt (generic) + strength.
// Fields: [generic, strength, form, category, costPrice, sellingPrice, company]
export const MEDICINES = [
  ["Tacrolimus", "2 mg", "Capsule", "Immunosuppressant", 40.5, 405.7, "Astellas Pharma"],
  ["Valganciclovir", "450 mg", "Tablet", "Anti-Viral", 84.4, 844, "Steadfast Medisales"],
  ["Methylcobalamin + Folic Acid", "", "Tablet", "Dietary Supplement", 8.09, 89, "Active Healthcare"],
  ["Etoricoxib", "60 mg", "Tablet", "Pain Killer", 9.08, 98, "Newmedd Pharmaceuticals"],
  ["Domperidone + Rabeprazole", "30+20 mg", "Capsule", "Antacids", 0, 97, "Newmedd Pharmaceuticals"],
  ["Etoricoxib", "90 mg", "Tablet", "Pain Relief", 9.9, 99, "Newmedd Pharmaceuticals"],
  ["Mometasone", "0.10% w/w", "Ointment", "Eczema", 0, 0, "Glenmark Pharma"],
  ["Trigaine", "200 ml", "Shampoo", "Hair Loss", 540, 540, ""],
  ["Tofacitinib", "5 mg", "Tablet", "Immunosuppressant", 35, 2100, "Cipla Ltd"],
  ["Cyclosporine", "50 mg", "Tablet", "Immunosuppressive", 0, 0, ""],
  ["Esomeprazole", "40 mg", "Tablet", "Antacids", 0, 79.55, "Zuventus Healthcare"],
  ["Torasemide", "10 mg", "Tablet", "Cardiovascular Disease", 0, 59, "Addii Biotech"],
  ["Spironolactone + Torasemide", "50+10 mg", "Tablet", "Cardiovascular Disease", 0, 59, "Addii Biotech"],
  ["Tacrolimus", "2 mg", "Capsule", "Prevention Of Organ Rejection In Transplant Patients", 0, 842.46, "Intas Pharmaceuticals"],
  ["Tacrolimus", "1 mg", "Capsule", "Prevention Of Organ Rejection In Transplant Patients", 0, 0, "Biokindle Lifesciences"],
  ["Tacrolimus", "2 mg", "Capsule", "Prevention Of Organ Rejection In Transplant Patients", 7.75, 775, "Alniche Life Sciences"],
  ["Acyclovir", "800 mg", "Tablet", "Anti-Viral", 0, 0, ""],
  ["Mycophenolate Sodium", "180 mg", "Tablet", "Immunosuppressant", 0, 0, "Alniche Life Sciences"],
  ["Darbepoetin Alfa", "40 mcg", "Injection", "Treatment Of Anemia Due To Chronic Kidney Disease", 2506, 2506, "Lupin Ltd"],
  ["Mycophenolate Sodium", "360 mg", "Tablet", "Immunosuppressant", 0, 0, ""],
  ["Sodium Bicarbonate", "500 mg", "Tablet", "Antacids", 3.92, 39.2, "Mysim Therapeutics"],
  ["Calcium Acetate", "667 mg", "Tablet", "Dietary Supplement", 0, 35, "Evervital Lifesciences"],
  ["Sodium Bicarbonate", "500 mg", "Tablet", "Antacids", 4.5, 45, "Ponoogun Health"],
  ["Aloe Vera + Vitamin E + Squalene", "", "Cream", "Moisturizer", 0, 438.5, "Dr Reddy'S Lab"],
  ["Protein Powder", "", "Powder", "Dietary Supplement", 3575, 3575, "Akcent Healthcare"],
  ["Darbepoetin Alfa", "40 mcg", "Injection", "Anemia", 0, 2240, "Evervital Lifesciences"],
  ["Sodium Valproate + Valproic Acid", "333+145 mg", "Tablet", "Anti Epileptic", 0, 0, ""],
  ["Recombinant Human Erythropoietin", "6000 iu", "Injection", "Treatment Of Anemia Due To Chronic Kidney Disease", 2500, 2500, "Intas Pharmaceuticals"],
  ["Sofosbuvir + Velpatasvir", "400+100 mg", "Tablet", "Chronic Hepatitis C Virus (HCV) Infection", 17500, 17500, "Dr Reddy'S Lab"],
  ["Dexlansoprazole + Domperidone", "60+30 mg", "Capsule", "Antacids", 19.9, 199, "MSN Labs"],
  ["Levofloxacin", "500 mg", "Tablet", "Antibiotics", 87, 500, "Lupin Ltd"],
  ["Ertapenem", "1000 mg", "Injection", "Antibiotics", 2400, 2400, "United Biotech"],
  ["Human Albumin", "20% / 100 ml", "Injection", "Fluid Replacement Therapy", 5240, 5240, "Baxter India Ltd"],
  ["Tulsi + Kali Mirch + Kantkari", "200 ml", "Syrup", "Cough", 160, 160, "Ashirvad Pharma"],
  ["Methylprednisolone", "8 mg", "Tablet", "Corticosteroid", 70, 70, "Vrinda Life"],
  ["Acebrophylline", "100 mg", "Capsule", "Asthma", 80, 80, "Hi-Cure Biotech"],
  ["Pilocarpine", "5 mg", "Tablet", "Miotics", 0, 349.99, "Tbg Pharma Ltd"],
  ["Fusidic Acid", "2% w/w", "Cream", "Skin Infections", 56.65, 56.65, "Sun Pharmaceutical"],
  ["Dutasteride + Silodosin", "0.5+8 mg", "Capsule", "Treatment Of Benign Prostatic Hyperplasia", 0, 0, "Genesis Biotech"],
  ["Lidocaine + Clotrimazole + Beclomethasone", "2%+1%+0.3%", "Ear Drop", "Anti Bacterial", 44, 44, "Kaizen Pharmaceuticals"],
  ["Eperisone + Aceclofenac", "150+200 mg", "Capsule", "Pain Killer", 24.9, 249, "Cnscure India"],
  ["Cyproheptadine", "2 mg", "Tablet", "Appetite Stimulant", 0, 0, ""],
  ["Methotrexate", "5 mg", "Tablet", "Rheumatoid Arthritis", 0, 0, ""],
  ["Vitamin D3 + Folic Acid + Alpha Lipoic Acid", "", "Tablet", "Dietary Supplement", 18.09, 189, "Jenburkt Pharma"],
  ["Kojic Acid + Niacinamide", "", "Cream", "Skin Care", 370, 370, "Zydillac Dermaceuticals"],

  ["Clindamycin + Nicotinamide", "1+4 w/w", "Gel", "Skin Care", 177, 177, "Abbott"],
  ["Pilocarpine", "5 mg", "Tablet", "Dry Mouth", 7.8, 78, "Sun Pharmaceutical"],
  ["Multivitamin", "", "Powder", "Dietary Supplement", 0, 295, "Alliance Overseas"],
  ["Dextromethorphan", "5 mg", "Lozenges", "Cough", 0, 108, "Glenmark"],
  ["Metformin + Vildagliptin", "1000+50 mg", "Tablet", "Anti-Diabetics", 16.3, 163.25, "Dr Reddy'S Lab"],
  ["Lactulose", "", "Powder", "Constipation", 0, 0, ""],
  ["Sildenafil", "100 mg", "Tablet", "Erectile Dysfunction", 29, 116, "Zydus Healthcare"],
  ["Lidocaine + Nifedipine", "1.5+0.3 w/w", "Ointment", "Anal Fissures", 166, 166, "Micro Lab Ltd"],
  ["Psyllium Husk", "", "Powder", "Laxative", 0, 0, ""],
  ["Diltiazem + Lidocaine", "2%+2% w/w", "Cream", "Anal Fissures", 0, 250, "Abbott"],
  ["Ketorolac", "10 mg", "Tablet", "Pain Killer", 0, 82, "Sun Pharmaceutical"],
  ["Atorvastatin Calcium", "10 mg", "Tablet", "Cardiovascular Disease", 0, 48, "Tn Med Pharma"],
  ["Metformin", "500 mg", "Tablet", "Anti-Diabetics", 0, 179, "Elder Pharmaceuticals"],
  ["Nebivolol", "5 mg", "Tablet", "Cardiovascular Disease", 0, 87, "Xemex Medic Science"],
  ["Dexamethasone", "0.5 mg", "Tablet", "Steroids", 0, 4.2, "Omega Pharmaceuticals"],
  ["Glimepiride + Metformin", "4+1000 mg", "Tablet", "Anti-Diabetics", 0, 133, "Sun Pharmaceutical"],
  ["Medroxyprogesterone Acetate", "5 mg", "Tablet", "Irregular Period", 6, 60.3, "Serum Institute Of India"],
  ["Dapagliflozin + Metformin + Sitagliptin", "10+1000+100 mg", "Tablet", "Anti-Diabetics", 0, 315, "Eris Lifesciences"],
  ["Cholecalciferol", "60000 iu", "Tablet", "Vitamin D Deficiency", 0, 94, "Sanofi India Ltd"],
  ["Dapagliflozin + Sitagliptin", "10+100 mg", "Tablet", "Anti Diabetic", 18, 180, "Dr Reddy'S Lab"],
  ["Insulin Lispro", "100 iu/ml", "Injection", "Antidiabetic", 0, 1688, "Eli Lilly And Company"],
  ["Aspirin + Rosuvastatin + Clopidogrel", "150+20+75 mg", "Capsule", "Cardiovascular Disease", 319, 319, "Macleods Pharma"],
  ["Methylcobalamin + Calcitriol", "", "Capsule", "Dietary Supplement", 1.5, 15, "Elisa Biotech"],
  ["Aceclofenac + Paracetamol + Serratiopeptidase", "100+325+15 mg", "Tablet", "Pain Killer", 0, 100, "Sycon Healthcare"],
  ["Pantoprazole", "40 mg", "Tablet", "Antacids", 0, 59, "Aryan Biotech"],
  ["Sacubitril + Valsartan", "24+26 mg", "Tablet", "Cardiovascular Disease", 25, 250, "Intas Pharmaceuticals"],
  ["Mycophenolate Sodium", "360 mg", "Tablet", "Immunosuppressant", 0, 1020.8, "Rpg Life Sciences"],
  ["Calcium", "667 mg", "Tablet", "Calcium Deficiency", 3.4, 34, "Rencord Life Sciences"],
  ["Mycophenolate Sodium", "180 mg", "Tablet", "Immunosuppressants", 0, 583.96, "Biocon"],
  ["Sodium Bicarbonate", "1000 mg", "Tablet", "Treatment Of Indigestion", 5.46, 82, "Genix Lifesciences"],
  ["Multivitamin", "", "Powder", "Dietary Supplement", 0, 0, ""],
  ["Calcitriol", "0.25 mcg", "Tablet", "Vitamin D3", 0, 102.85, "Hospimax Healthcare"],
  ["Fluconazole", "200 mg", "Tablet", "Anti Fungal", 0, 0, ""],
  ["Tacrolimus", "0.5 mg", "Capsule", "Prevention Of Organ Rejection In Transplant Patients", 20.64, 206.41, "Biocon"],
  ["Domperidone + Rabeprazole", "30+20 mg", "Capsule", "Nausea Acidity", 0, 71, "D.S. Lab"],
  ["Telmisartan + Chlorthalidone", "80+12.5 mg", "Tablet", "Cardiovascular Disease", 20.01, 201, "Micro Labs Ltd"],
  ["Methylcobalamin + L-Methyl Folate", "", "Tablet", "Dietary Supplement", 0, 0, "Danlion Pharma"],
  ["Benidipine + Nebivolol", "4+5 mg", "Tablet", "Cardiovascular Disease", 16.08, 168, "Oldmed Healthcare"],
  ["Sevelamer", "800 mg", "Tablet", "Phosphate Binders", 16.05, 165, "Steadfast Medisales"],
  ["Insulin Glargine", "100 iu/ml", "Injection", "Anti Diabetic", 782.13, 782.13, "Eris Lifesciences"],
  ["Human Insulin", "40 iu/ml", "Injection", "Anti Diabetic", 157, 157, "Eris Lifesciences"],
  ["Recombinant Human Erythropoietin", "5000 iu", "Injection", "Treatment Of Anemia Due To Cancer Chemotherapy", 1991, 1991, "Zydus Cadila"],
  ["Pitavastatin", "4 mg", "Tablet", "Cardiovascular Disease", 19.9, 199, "Nyg Pharmaceuticals"],
  ["Ertapenem", "1000 mg", "Injection", "Antibiotic", 0, 2400, "United Biotech"],
  ["Terlipressin", "1 mg", "Injection", "Bleeding", 0, 0, ""],
  ["Etanercept", "25 mg", "Injection", "Rheumatoid Arthritis", 3500, 3500, "Cipla Ltd"],
  ["Pregabalin + Nortriptyline", "75+10 mg", "Tablet", "Neuropathic Pain", 140, 140, "Rejli Healthcare"],

  ["Ivabradine", "10 mg", "Tablet", "Cardiovascular Disease", 13.5, 135, "Lupin Ltd"],
  ["Antioxidant + Multivitamin + Multimineral", "", "Tablet", "Dietary Supplement", 0, 0, "Glenburg Healthcare"],
  ["Peppermint Oil", "", "Capsule", "Treat Irritable Bowel Syndrome", 9, 135, "Seagull Pharma"],
  ["Levocetirizine + Montelukast", "5+10 mg", "Tablet", "Anti Allergics", 0, 0, ""],
  ["Tolperisone + Diclofenac", "150+50 mg", "Tablet", "Muscle Relaxant", 0, 0, ""],
  ["Sitagliptin", "100 mg", "Tablet", "Anti Diabetic", 15, 150, "Eris Lifesciences"],
  ["Levofloxacin", "500 mg", "Tablet", "Antibiotic", 87, 87, "Lupin Ltd"],
]
