// Radiology / imaging exam catalog (from SegregatedInvestigations - Radiology column).
export const RADIOLOGY_EXAMS = [
  // ── X-RAY ──
  "X-Ray Chest PA View","X-Ray Chest","X-Ray Chest AP View","X-Ray Chest Lateral View","X-Ray Chest Left Lateral View","X-Ray Chest Right Lateral","X-Ray Chest with Lower Ribs","X-Ray Chest with Brace Ribs AP View","X-Ray Abdomen - Supine","X-Ray Abdomen - Standing","X-Ray Abdomen - Erect AP View","X-Ray Abdomen - KUB","X-Ray Abdomen - Cross Table","X-Ray Abdomen Loaded Colon","X-Ray Abdomen Lying Position","X-Ray KUB",
  "X-Ray Ankle - AP","X-Ray Ankle - AP Left","X-Ray Ankle - AP Right","X-Ray Ankle - AP/Lateral Left","X-Ray Ankle - AP/Lateral Right","X-Ray Ankle - Lateral","X-Ray Ankle - Oblique","X-Ray Ankle - AP (Mortise View)","X-Ray Arm - AP","X-Ray Arm - AP Left","X-Ray Arm - AP Right","X-Ray Arm - Lateral","X-Ray Arm - Oblique","X-Ray Arm AP/Lateral",
  "X-Ray Base of the Skull","X-Ray Both SI Joint","X-Ray Both SI Joint - Left","X-Ray Both SI Joint - Right","X-Ray Carpal Tunnel View","X-Ray Cervical Spine","X-Ray Cervical Spine AP/Lateral","X-Ray Cervical Spine Lateral View","X-Ray Cervical Spine Flexion and Extension","X-Ray Cervical Spine AP/Lateral Mouth Open","X-Ray DL Spine","X-Ray DL Spine AP & Lateral (Standing)","X-Ray Dorsal Spine","X-Ray Dorsal Spine AP View","X-Ray Dorsal Spine Lateral View",
  "X-Ray Elbow - AP","X-Ray Elbow - AP Left","X-Ray Elbow - AP Right","X-Ray Elbow - Lateral","X-Ray Elbow - Oblique","X-Ray Elbow AP/Lateral","X-Ray Femur - Lateral Left","X-Ray Femur - Lateral Right","X-Ray Femur AP and Lateral","X-Ray Foot - AP","X-Ray Foot - AP Left","X-Ray Foot - AP Right","X-Ray Foot - Lateral","X-Ray Foot - Oblique","X-Ray Forearm - AP","X-Ray Forearm - Lateral","X-Ray Forearm - Oblique","X-Ray Forearm with Wrist AP/Lateral",
  "X-Ray Hand - AP","X-Ray Hand - AP Left","X-Ray Hand - AP Right","X-Ray Hand - Lateral","X-Ray Hand - Oblique","X-Ray Hand & Wrist for Bone Age","X-Ray Knee - AP","X-Ray Knee - AP Left","X-Ray Knee - AP Right","X-Ray Knee - AP/Lateral","X-Ray Knee - Lateral","X-Ray Knee - Oblique","X-Ray Knee Standing","X-Ray Knee Skyline View","X-Ray Both Knee AP and Lateral Standing","X-Ray Both Knee Standing","X-Ray Bilateral Knee",
  "X-Ray Lumbosacral Spine","X-Ray LS Spine AP/Lateral","X-Ray LS Spine AP & Lateral","X-Ray LS Spine (Standing)","X-Ray LS Spine Flexion Extension","X-Ray Tibia - AP","X-Ray Tibia - AP Left","X-Ray Tibia - AP Right","X-Ray Tibia - Lateral","X-Ray Tibia (Leg) AP Lateral View","X-Ray Pelvis","X-Ray Pelvis AP View","X-Ray Pelvis AP/Lateral View","X-Ray Pelvis with Both Hips","X-Ray Pelvis with Bilateral SI Joint AP","X-Ray Hip","X-Ray Hip Joints","X-Ray Hip Joint AP/Lateral","X-Ray Bilateral Hip",
  "X-Ray Shoulder AP View","X-Ray Shoulder AP/Lateral","X-Ray Left Shoulder Joint - AP & Lateral","X-Ray Right Shoulder AP View","X-Ray Both Shoulder True AP","X-Ray Skull","X-Ray Skull AP/Lateral View","X-Ray Skull Lateral View","X-Ray Wrist","X-Ray Wrist AP View","X-Ray Bilateral Wrist with Hand","X-Ray Whole Spine","X-Ray Whole Spine AP and Lateral","X-Ray Whole Spine Standing AP and Lateral","X-Ray Nasal Bone","X-Ray Nasal Bone Lateral View","X-Ray Nasal Bones","X-Ray PNS","X-Ray PNS Water View","X-Ray Pns Water View with Open Mouth","X-Ray STN (Soft Tissue Neck) Lateral","X-Ray STN AP","X-Ray Neck AP/Lateral View","X-Ray Mastoid","X-Ray Mandible AP & Lateral","X-Ray Coccyx AP and Lateral View","X-Ray Sacrum Lateral View","X-Ray Sacrococcyx Lateral View","X-Ray Clavicle - AP View","X-Ray Scapula AP View","X-Ray Thoracic Spine AP & Lateral","X-Ray Thumb","X-Ray Heel Lateral","X-Ray Calcaneus AP & Lateral","X-Ray Cephalogram","X-Ray Lateral Cephalogram","X-Ray Cheek","X-Ray Face AP/Lateral","X-Ray Adenoid Lateral","X-Ray Bone Age","X-Ray Defecography","X-Ray Spinogram","X-Ray Scanogram AP View","X-Ray Bilateral Lower Limb Scanogram","X-Ray Whole Abdomen Erect AP","Chest X-Ray","X-Ray Both Foot AP/Lateral (Standing)","X-Ray Both Thigh - AP View","X-Ray Both Femur - AP View",

  // ── MRI ──
  "MRI - Brain","MRI - Brain + Angio","MRI - Brain + Orbit","MRI - Brain + Veno","MRI - Brain with Contrast","MRI - Brain Plain","MRI - Brain Plain and Contrast","MRI - Abdomen","MRI - Angiography","MRI - Ankle Left","MRI - Ankle Right","MRI - Base of Skull to Inlet of Thorax","MRI - Breast Left","MRI - Breast Right","MRI - Bilateral Breast","MRI - Cardiac","MRI - Cervical Spine","MRI - Cervical Spine Plain","MRI - Cisternography","MRI - CSF flow Study","MRI - CV Junction","MRI - DL Spine","MRI - Dorsal Spine","MRI - Fistulogram","MRI - Functional","MRI - Hip Joint","MRI - Both Hip Joints","MRI - Knee Left","MRI - Knee Right","MRI - Both Knee","MRI - Limb Left","MRI - Limb Right","MRI - Lumbar Spine","MRI - Lumbosacral Spine","MRI - LS Spine","MRI - LS Spine (3T)","MRI - Neck Left","MRI - Neck Right","MRI - Soft Tissue Neck","MRI - Orbit","MRI - Pelvis","MRI - Pelvis with Contrast","MRI - PNS","MRI - Prostate","MRI - MP-MRI Prostate","MRI - Shoulder Joint","MRI - Shoulder Left","MRI - Shoulder Right","MRI - Both Shoulder","MRI - SI Joint Left","MRI - SI Joint Right","MRI - Both SI Joint","MRI - Spectroscopy","MRI - Spine","MRI - Whole Spine","MRI - Whole Spine (3T)","MRI - Thorax Left","MRI - Thorax Right","MRI - TM Joint Left","MRI - TM Joint Right","MRI - Tractography","MRI - Urography/Myelography","MRI - Wrist Left","MRI - Wrist Right","MRI - Scan of Brain and Pituitary","MRI - Brain for Pituitary","MRI - Pituitary with Contrast","MRI - Sella","MRI - Face","MRI - Inner Ear","MRI - Brachial Plexus","MRI - Lumbosacral Plexus","MRI - Both Hands","MRI - Foot","MRI - Left Foot","MRI - Both Feet","MRI - Sacrococcygeal Region","MRI - Coccygeal Region","MRI - Sacrum with Coccyx","MRI - Defecogram","MRI - Rectum","MRI - Buttock Region","MRI - Gluteal Region","MRI - Leg","MRI - Spinal Cord","MRI - Skull","MRI - Sialography","MRI - Both Knee Joint Screening","MRI - Bilateral Sacroiliac Joints with Whole Spine Screening","MRI - Whole Abdomen with Rectal Protocol","MRI - Whole Abdomen Plain & Contrast","MRI - Diffusion Study","MRI - SPA Protocol","MRI - Cochlear Nerve","MRI - PNS and Orbit","MRI - Brain with PNS","MRI - Brain with Screening Whole Spine",

  // ── CT ──
  "CT - Abdomen","CT - Abdomen and Pelvis","CT - Bone Densitometry","CT - Cardiac","CT - Chest","CT - Chest with Contrast","CT - Cisternography","CT - Coronary Angiography","CT - Coronary Calcium Study","CT - CV Junction","CT - DL Spine Plain","CT - DL Spine Plain + Contrast","CT - Elbow Left","CT - Elbow Right","CT - Head/Brain Plain","CT - Head/Brain Plain + Contrast","CT - Brain with Contrast","CT - Brain Plain","CT - HRCT Chest","CT - HRCT Lung","CT - HRCT PNS","CT - HRCT Temporal Bone","CT - HRCT Thorax","CT - KUB Plain","CT - KUB Plain + Contrast","CT - Left Limb","CT - Right Limb","CT - Lung","CT - Neck","CT - Neck (Plain + Contrast)","CT - Orbit","CT - Parotid Region","CT - Pelvis","CT - Perfusion Study","CT - PNS","CT - PNS Coronal","CT - PNS Coronal and Axial","CT - Shoulder Left","CT - Shoulder Right","CT - Skull","CT - Spine Plain","CT - Spine Contrast + Plain","CT - Thorax","CT - Thorax (Contrast)","CT - TMJ","CT - Virtual Bronchoscopy","CT - Virtual Colonoscopy","CT - Whole Body","CT - Coronary Angiogram","CT - Scan","CT - Sinus","CT - Face","CT - Face with 3D Reconstruction","CT - KUB","CT - Pyelogram","CT - Pulmonary Angiography","CT - Renal Angiography","CT - Angiography Abdomen","CT - Angiography Lower Limb","CT - Angiography Head","CT - Angiography Head and Neck","CT - Angiography Brain & Carotids","CT - Enterography","CT - Urogram","CT - Triphasic Upper Abdomen","CT - Triphasic Scan","CT - Liver Attenuation Index (LAI)","CT - Scanogram for Limb Length Estimation","CT - Whole Abdomen Contrast","CT - Head with Cervical Spine","CT - Calcium Score","CT - Brain Screening",

  // ── USG / Ultrasound ──
  "USG Abdomen","USG Abdomen and Pelvis","USG Whole Abdomen","USG Whole Abdomen and Pelvis","USG Whole Abdomen/KUB","USG KUB","USG KUB with Post Void Residual Urine","USG Kidney","USG Ankle Joint Left","USG Ankle Joint Right","USG Congenital Anomaly Scan","USG Fistulography Left","USG Knee Joint Left","USG Knee Joint Right","USG Left Hip","USG Right Hip","USG Bilateral Hip","USG Left Shoulder","USG Right Shoulder","USG Local","USG Neck","USG Obstetric","USG Orbit Left","USG Orbit Right","USG Parotid","USG Bilateral Parotid Region","USG Pelvis","USG Pelvis (TVS)","USG Prostate","USG Scrotum","USG Scrotum with Doppler","USG Skull","USG Testes","USG Thyroid","USG Trans Rectal Sonography","USG Trans Vaginal Sonography","USG Breast","USG Both Breast","USG Bilateral Breast","USG B/L Breast and Axilla","USG Chest","USG Left Chest","USG Right Chest","USG Cranium","USG Cranial","USG Doppler","USG Inguinoscrotal","USG B/L Inguinoscrotal Region","USG Soft Tissue Parts","USG Guided FNAC","USG Guided FNAC for Thyroid Nodules","USG Guided Biopsy","USG Guided Trucut Biopsy","USG NT Scan","USG NT/NB Scan","USG Growth Profile","USG Growth Scan","USG Anomaly Scan","USG Level 1 Early Anomaly Scan","USG Level 2 Anomaly Scan","USG Early Pregnancy Scan","USG Dating Scan","USG Crown-Rump Length (CRL)","USG Follicular Monitoring","USG TVS for Follicle Monitoring (AFC Only)","USG AFC (Antral Follicle Counts)","USG Uterus","USG Vulva","USG Biophysical Profile","USG Fetal Well Being","USG Obstetric for Fetal Well Being","USG Obstetric Color Doppler","USG Routine Obstetric","USG Bilateral Inguinal Region","USG Right Inguinal Region","USG Bilateral Feet","USG Right Ankle","USG Right Foot","USG Right Wrist","USG Right Lower Limb","USG Bilateral Hands","USG Gallbladder","USG Liver","USG Pancreas","USG Bilateral Adrenal Gland","USG Sternum","USG Axilla","USG Bilateral Axilla","USG Soft Tissue Breast","USG Soft Tissue Axilla","USG Chest Wall","USG Chest Upper Ribs","Musculoskeletal Ultrasound","Endoscopic Ultrasound","Endobronchial Ultrasound","Transrectal Ultrasound Scan","Antenatal Ultrasound","Ultrasound Joints",

  // ── Doppler ──
  "Color Doppler","Colour Doppler","Local Doppler","Carotid Doppler","Carotid Ultrasound","Doppler of Bilateral Carotids","Lower Limb Arterial Doppler Left","Lower Limb Arterial Doppler Right","Lower Limb Venous Doppler Left","Lower Limb Venous Doppler Right","Bilateral Lower Limb Arterial and Venous Doppler","Bilateral Lower Limb Venous Doppler","Venous Doppler Left Leg","Venous Doppler Right Leg","Venous Doppler Left Upper Limb","Venous Doppler Right Upper Limb","Arterial Doppler Right Lower Limb","Arterial Doppler Left Lower Limb","Arterial Doppler Both Legs","Doppler Arterial Right Upper Limb","Doppler Venous Right Upper Limb","Renal Artery Doppler","Bilateral Renal Doppler","Hepatic Venous Doppler","Vertebral Artery Doppler","Temporal Artery Doppler","Penile Doppler","Scrotal Doppler","IVC (Inferior Vena Cava) Doppler","Doppler Echocardiography","Transcranial Doppler","Color Doppler Bilateral Carotid Artery","Cardiac Doppler Test - Whole View",

  // ── PET / Nuclear / DEXA / Mammography / Other ──
  "PET CT Scan","PET Scan","PET Whole Body Scan","PET Brain Scan","Whole Body FDG PET CT Scan","DOTANOC PET CT Scan","FDG PET CT Brain","PSMA PET Scan / CT","DOPA PET Scan","Triple Phase PET CT","PET CT with Contrast","Positron Emission Tomography Scan","SPECT Scan","Single-Photon Emission Computed Tomography","Bone Scan","HIDA Scan","Hepatobiliary Scan","DMSA (Dimercapto Succinic Acid)","DTPA Scan","Lung CT Scan","Heart Scan (Coronary Calcium Scan)","Coronary Calcium Scan","Coronary Angiogram","Computerized Tomography (CT) Urogram","DEXA Scan","DEXA Bone Scan","DEXA for Bones (Spine/Femur/Wrist)","DEXA Scan Spine","DEXA Scan Hip","DEXA Scan Forearm","DEXA Scan Bilateral Hip","Whole Body DEXA Scan","Bone Densitometry DEXA Hip","Bone Densitometry DEXA Spine","Bone Density 3 Sites","Mammography","Bilateral Mammography","3D Mammography","3D Mammogram","Bilateral 3D Mammogram","Sonomammography","Bilateral Sonomammography","Breast Mammography","Hysterosalpingography (HSG)","Intravenous Urography","Micturating Cysto-Urethrogram (MCU)","Retrograde Pyelogram","Barium Swallow Test","Barium Stomach Duodenum","Small Bowel Series","Enteroclysis","Sinogram AP and Lateral View","T-Tube Cholangiogram","2D Echo with Doppler","Stress Echocardiogram","Exercise Stress Echocardiogram","Transesophageal Echocardiogram (TEE)","Fetal Echo","Screening Echo","Echocardiography","Nerve Conduction Studies (NCS)","Nerve Conduction Velocity (NCV)","EMG Study","Magnetic Resonance Venography (MRV)","Magnetic Resonance Cholangiopancreatography (MRCP)","CT Angiography","MR Angiography (MRA)","CT Coronary Angiogram (CTCA)","Magnetic Resonance Elastography","Magnetic Resonance Imaging","12-Lead Electrocardiogram (ECG)","Intracardiac Electrophysiology Study (EPS)","Pulmonary Function Test","Spirometry",
]
